#!/bin/bash

. /usr/share/preupgrade/common.sh

#END GENERATED SECTION
AIDE_LOG="/var/log/aide/aide.log"
FOUND=0

# Aide installed but never run
if [[ ! -f $AIDE_LOG ]]; then
    log_info "The AIDE tool was installed but never run."
    exit $RESULT_INFORMATIONAL
fi

log_medium_risk "The AIDE tool is being used for 'guarding' the system integrity."
exit $RESULT_FAIL
