#!/bin/bash
. /usr/share/preupgrade/common.sh

#END GENERATED SECTION

grep -E "^\s*AuthorizedKeysCommand /usr/libexec/openssh/ssh-keycat" /etc/ssh/sshd_config

[[ $? -ne 0 ]] && {
  log_medium_risk "The ssh-keycat files are moved to the openssh-keycat package."
  echo "The following ssh-keycat files are moved to the openssh-keycat package:
- /etc/pam.d/ssh-keycat
- /usr/libexec/openssh/ssh-keycat
- /usr/share/doc/openssh-server-5.3p1/HOWTO.ssh-keycat

To use ssh-keycat, install the openssh-keycat package.
" >> solution.txt
  exit $RESULT_FAIL
}


log_high_risk "ssh-keycat is used as a part of the openssh-keycat package in Red Hat Enterprise Linux 7."
msg="ssh-keycat is moved to its own openssh-keycat package, which is"
msg+=" automatically installed by the post-upgrade script in case the"
msg+=" repository with the package is available during downloading of the"
msg+=" packages by the redhat-upgrade-tool. However, the repository is usualy"
msg+=" available only for subscribed Red Hat Enterprise Linux 7 system. You"
msg+=" need to create your own repository with the ssh-keycat package or"
msg+=" change settings of your system so you will be able to connect using ssh"
msg+=" without the ssh-keycat and change the settings back manually after"
msg+=" upgrade will be finished and ssh-keycat will be installed on the target"
msgě=" system."
echo "$msg" >> solution.txt

cp install-openssh-keycat.sh $POSTUPGRADE_DIR/install-openssh-keycat.sh
exit $RESULT_FAIL

