#!/bin/bash

. /usr/share/preupgrade/common.sh

#END GENERATED SECTION
[ -f "$VALUE_RPM_RHSIGNED" ] || {
  log_error "Generic common files are missing."
  exit $RESULT_ERROR
}

get_dist_native_list | grep -qe '-debuginfo$' || exit_pass

log_high_risk "Debuginfo packages are detected on the system; the debuginfo repository has to be provided as a parameter to redhat-upgrade-tool for the proper upgrade."
log_slight_risk "Dependencies might cause incompleteness of the debugging tree after the upgrade. You will probably need to install additional debuginfos after the upgrade."
exit_fail
