#!/bin/bash

. /usr/share/preupgrade/common.sh

#END GENERATED SECTION


CLEANCONF_D="$VALUE_TMP_PREUPGRADE/cleanconf"
SSHD_CONFIG_FILE="/etc/ssh/sshd_config"
CLEANCONF_SSHD="${CLEANCONF_D}${SSHD_CONFIG_FILE}"
RESULT=$RESULT_PASS

cp -a --parent $SSHD_CONFIG_FILE $CLEANCONF_D

if grep -q "^[[:space:]]*RequiredAuthentications2" $SSHD_CONFIG_FILE; then
    msg="* RequiredAuthentications2 is replaced by AuthenticationMethods in"
    msg+=" $CLEANCONF_SSHD. If you want to fix the config file yourself, type:"
    msg+="\n  # sed -i -e 's/^[[:space:]]*RequiredAuthentications2/AuthenticationMethods/i' ${SSHD_CONFIG_FILE}"
    msg+="\nFor more information about AuthenticationMethods, see the SSHD_CONFIG(5) man page."
    echo -e "$msg\n" >> solution.txt

    #FIXME: fix text and the logic - slight risk + fixed?...
    log_slight_risk "RequiredAuthentication2 will be replaced by AuthenticationMethods."

    sed -i -e 's/^\([[:space:]]*\)RequiredAuthentications2/\1AuthenticationMethods/i' $CLEANCONF_SSHD \
      && RESULT=$RESULT_FIXED || RESULT=$RESULT_FAIL
fi

if grep -q "^[[:space:]]*RequiredAuthentications1" $SSHD_CONFIG_FILE; then
    echo -e "\n* RequiredAuthentications1 will not be supported anymore.\n" >> solution.txt
    log_slight_risk "RequiredAuthentications1 will not be supported anymore."
    exit $RESULT_FAIL
fi

if grep -q -i "^[[:space:]]*AuthorizedKeysCommand[[:space:]]" $CLEANCONF_SSHD; then
    if grep -q -i "^[[:space:]]*AuthorizedKeysCommandRunAs[[:space:]]" $CLEANCONF_SSHD; then
        msg="* The AuthorizedKeysCommandRunAs option will not be supported in"
        msg+=" Red Hat Enterprise Linux 7 anymore and it will be replaced by"
        msg+=" AuthorizedKeysCommandUser. This option is replaced in"
        msg+=" [link:cleanconf/$SSHD_CONFIG_FILE]. If you want to fix the"
        msg+=" config file yourself, type:"
        msg+="\n  # sed -i -e 's/^[[:space:]]*AuthorizedKeysCommandRunAs\([[:space:]]\)/AuthorizedKeysCommandUser\1/i' $SSHD_CONFIG_FILE"
        msg+="\nFor more information about AuthorizedKeysCommand, see the SSHD_CONFIG(5) man page."
        echo -e "$msg\n" >> solution.txt

        #FIXME: again
        log_slight_risk "AuthorizedKeysCommandRunAs will be replaced by AuthorizedKeysCommandUser."
        sed -i -e 's/^\([[:space:]]*\)AuthorizedKeysCommandRunAs\([[:space:]]\)/\1AuthorizedKeysCommandUser\2/i' $CLEANCONF_SSHD \
          && RESULT=$RESULT_FIXED || RESULT=$RESULT_FAIL
    else
        msg="* The AuthorizedKeysCommand option requires the AuthorizedKeysCommandUser"
        msg+=" option, see the SSHD_CONFIG(5) man page."
        msg+=" 'AuthorizedKeysCommandUser %u' is added into [link:cleanconf/$SSHD_CONFIG_FILE]."
        msg+=" If you want to fix the config file yourself, type:"
        msg+="\n  # echo 'AuthorizedKeysCommandUser %u' >> $SSHD_CONFIG_FILE"
        msg+="\nFor more information about AuthorizedKeysCommandUser, see the SSHD_CONFIG(5) man page."
        echo -e "$msg\n" >> solution.txt

        #FIXME: ...
        log_slight_risk "AuthorizedKeysCommandUser will be added into $CLEANCONF_SSHD."

        echo 'AuthorizedKeysCommandUser %u' >> $CLEANCONF_SSHD
        RESULT=$RESULT_FIXED
    fi
fi

exit $RESULT

