#!/bin/bash

. /usr/share/preupgrade/common.sh

#END GENERATED SECTION

FOUND=0
COLLECTIONS=`scl --list`
if [ x"$COLLECTIONS" == "x" ]; then
	exit_pass
fi
log_info "A list of installed collections:"
for collection in $COLLECTIONS
do
    log_info "$collection"
done

log_high_risk "Found installed collections."
exit_fail
