#!/bin/bash

. /usr/share/preupgrade/common.sh
#END GENERATED SECTION

FOUND=0
if [ ! -f "$VALUE_RPM_QA" ]; then
    log_error "The $VALUE_RPM_QA fiel with all RPM packages is required."
    exit_error
fi

PKGS=`grep "devtoolset-" $VALUE_RPM_QA | awk '{print $1}'`
if [ x"$PKGS" != "x" ]; then
    log_high_risk "The list of installed Red Hat Developer Toolset packages:"
    for pkg in $PKGS
    do
        log_info "$pkg"
    done
    exit_fail
fi

exit_pass
